.\" Manpage for simeis-server-jla.
.\" Contact leo@sdv.net to correct errors or typos.
.TH man 8 "24 October 2025" "1.0" "simeis-server-jla man page"
.SH NAME
simeis-server-jla \- run server
.SH DESCRIPTION
simeis-server-jla is a game server.
.SH OPTIONS
The simeis-server-jla does not take any options. However, you can supply username.
.SH SEE ALSO
cmatrix(2.0-3),
.SH BUGS
No known bugs.
.SH AUTHOR
B. Leo(leo@sdv.net)