name: Auto Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        with:
          branchName: "${{ github.event.issue.label[0] }}-${{ github.event.issue.title }}"
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
