name: Create Release
on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle packages
        id: cache-deps
        continue-on-error: true
        uses: actions/cache@v4
        env:
          cache-name: cache-deps
        with:
          path: |
            target
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Typst CLI
        run: cargo install typst-cli


      - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        name: Build dependencies
        run: echo "building dependencies"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Generate changelog from merged PRs
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "## 🚀 Changes" >> $GITHUB_ENV
          git log --oneline --merges --first-parent origin/main..HEAD | \
            grep -oP "Merge pull request #\K\d+" | \
            while read pr; do
              title=$(gh pr view $pr --json title -q .title)
              echo "- $title ([#$pr](https://github.com/${{ github.repository }}/pull/$pr))" >> $GITHUB_ENV
            done
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release the new binaries
        uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          name: "Latest Commit, that compiles"
          body: |
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ${{ env.CHANGELOG }}

            ---
          files: |
            target/release/simeis-server
            doc/output.pdf
          clear_attachments: true