name: Create Release
on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle packages
        id: cache-deps
        continue-on-error: true
        uses: actions/cache@v4
        env:
          cache-name: cache-deps
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Typst CLI
        run: cargo install typst-cli


      - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        name: Build dependencies
        run: echo "building dependencies"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Docker Build & Save
        run: docker build -t simeis-server . && docker image save simeis-server > simeis-server.tar

      - name: Docker Login
        run: echo "${{ secrets.GH_SECRET_KEY }}" | docker login -u litchipi --password-stdin

      - name: Docker push
        run: |
          docker build -t litchipi/simeis-server-jla . 
          docker push litchipi/simeis-server-jla

      - name: Create debian pkg
        run: |
          mkdir -p debian/usr/bin
          mkdir -p debian/usr/share/man/man1
          mkdir -p debian/etc/systemd/system
          mkdir -p debian/DEBIAN
          cp ./debian/control debian/DEBIAN/
          cp ./target/release/simeis-server ./debian/usr/bin
          chmod 755 ./debian/usr/bin/simeis-server
          cp ./debian/simeis-server-jla.1 ./debian/usr/share/man/man1/
          gzip -9 ./debian/usr/share/man/man1/simeis-server-jla.1
          cp ./debian/simeis-server-jla.service debian/etc/systemd/system/
          chmod 644 debian/etc/systemd/system/simeis-server-jla.service
          cp ./debian/postinst debian/DEBIAN/
          chmod 755 debian/DEBIAN/postinst
          find debian -type d -exec chmod 755 {} \;
          dpkg-deb --build debian
          mv debian.deb simeis-server-jla.1-1_all.deb

      - name: Upload deb to VM
        continue-on-error: true
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -P 22222 \
              -i ./private_key \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ./simeis-server-jla.1-1_all.deb \
              leo@78.123.114.124:/home/student/
          rm -f private_key

      - name: Release the new binaries
        uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          name: "Latest Commit, that compiles"
          body: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ${{ env.CHANGELOG }}

            ---
          files: |
            target/release/simeis-server
            doc/output.pdf
            simeis-server.tar
            simeis-server-jla.1-1_all.deb
          clear_attachments: true