name: Create Release
on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle packages
        id: cache-deps
        continue-on-error: true
        uses: actions/cache@v4
        env:
          cache-name: cache-deps
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Typst CLI
        run: cargo install typst-cli


      - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        name: Build dependencies
        run: echo "building dependencies"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Aquire code
        if: always()
        uses: actions/checkout@v2
      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release the new binaries
        uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          name: "Latest Commit, that compiles"
          body: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ${{ env.CHANGELOG }}

            ---
          files: |
            target/release/simeis-server
            doc/output.pdf
          clear_attachments: true