name: Heavy testing

on:
  pull_request:
    types: ["closed"]
    branches:
      - main
  workflow_dispatch:

jobs:
  heavy-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run heavy tests - Scenario 1
        run: python3 example/tests/run-all-tests.py