name: Check dependencies

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check for outdated dependencies
        id: check
        run: |
          output=$(cargo update --dry-run 2>&1)
          echo "$output"
          if echo "$output" | grep -q "Updating"; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Cargo dependencies
        if: steps.check.outputs.update_needed == 'true'
        run: cargo update

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cargo-update-${{ github.run_id }}
          title: "chore: update Rust dependencies"
          body: "This PR updates Cargo dependencies to their latest compatible versions."
          commit-message: "chore: update Rust dependencies"
          add-paths: |
            Cargo.lock
